### ISSUE TITLE
3-wide tile width too short when using "noPadding: true"

### ISSUE THREAD

**Issue by ryantrip** [DBuit/Homekit-panel-card#82]
As seen in the first screenshot. I see your calculation here for the "noPadding" option is as follows:

`calc((var(--tile-width, 100px) * 3) + (20px * 2) + (5px * 3) + 20px - 4px)`

<img width="557" alt="Screen Shot 2020-09-08 at 11 30 15 PM" src="https://user-images.githubusercontent.com/24561062/92562848-7a719100-f22b-11ea-97a4-23592ee95e45.png">

I find that adding + 4 instead of subtracting at the end fixes the issue:

`calc((var(--tile-width, 100px) * 3) + (20px * 2) + (5px * 3) + 20px + 4px)`

<img width="548" alt="Screen Shot 2020-09-08 at 11 34 15 PM" src="https://user-images.githubusercontent.com/24561062/92563140-f2d85200-f22b-11ea-9342-6cc6343319c8.png">

**Comment by cs42** [comment]
I think it basically needs to be this

`calc((var(--tile-width, 100px) * 3) + (20px * 3) + (6px * 2) + 6px)`

single button width * 3 + single button padding sum * 3 + plust single button margin sum * 2 (the space betweeb);  I just don't understand, why the +6px is needed, but it is for me to fit. The same calculation would be needed for all other spanning buttons, so basically for a N column button:

`calc((var(--tile-width, 100px) * N) + (20px * N) + (6px * (N-1)) + Z)`

I don't if Z is always 6px, I would, if I knew the reason for this addition...

**Comment by cs42** [comment]
> `calc((var(--tile-width, 100px) * N) + (20px * N) + (6px * (N-1)) + Z)`

Though my calculations seem plausible, it only works on desktop but not on Android. There the box is too small.

**Comment by wtrbuit** [comment]
@ryantrip This should be fixed in the latest [release 0.5.9](https://github.com/DBuit/Homekit-panel-card/releases/tag/0.5.9). Can you verify this?

**Comment by ryantrip** [comment]
Apologies for the late reply, the issue still appears to be prevalent.
